### ISSUE TITLE
Validate message when publishing

### ISSUE THREAD

**Issue by thorncp** [thoughtbot/velveteen#12]
This would aid with testing the production of messages because we'd get the error immediately where the data is invalid, instead of further down the pipeline where it's easier to miss.

**Comment by thorncp** [comment]
If we continue with the home-rolled schema validation approach, we could transition from having schemas attached to workers to having them attached to routing keys. That would allow the publishing side to validate the message without needing to know what workers exist.

**Comment by thorncp** [comment]
Another option could be to use something like [Avro](https://avro.apache.org/) to define our schema(s). I'm not sure what the details of that would look like yet.

**Comment by whyderrick** [comment]
@thorncp, @sweta and I are starting to work on this now. Comprehension check: 

We're currently validate messages when consuming them and want to also validate when producing them. There are 3 approaches.

1. We could do something like add a new attribute `publish_message_schema` to the Worker class and add a `maybe_validate_schema` that validates when publish is called.
2. We could introduce a class for routing keys where they have schemas attached to them. We'd probably want to break the API to attach them to workers if we do that. 
3. We could use Avro/Protobuf/other tool. I don't know the lay of the land of these tools well enough yet to prefer a particular one to homegrown schemas, but I do think allowing for them makes lots of sense.  

That accurate to what you were laying out above? If so, we'll move forward with option 2 and look into Avro.

**Comment by thorncp** [comment]
Y'all's comprehension seems pretty good!

1. I'd like to avoid adding more attributes, if possible.
2. This is intriguing and might fit in well with what I had in my head (below). I'd be interested to hear more about that approach.
3. For now, I think it makes sense to continue with JSON Schema and not explicitly support these other tools.

The unvalidated idea I've had in my head is to have a convention of naming the schema files after the routing keys. Producing and consuming both require a routing key, so the hooks in those places could look for a schema that matches and use it. A side affect, I think, would be removing the `message_schema` attribute from the worker class, which would be nice.
